/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
  const ElTag: typeof import('element-plus/es')['ElTag']
}
